In [3]:
import torch

In [4]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-65, -16, -72, -77,  48,  88])

In [5]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
input = torch.empty(2,3)
input

tensor([[-4.6984e+03,  7.2727e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3,10, steps = 7)
linspace

tensor([ 3.0000,  4.1667,  5.3333,  6.5000,  7.6667,  8.8333, 10.0000])

In [11]:
logspace = torch.logspace(start = -10, end = 10,steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
empty = torch.empty(2,3)
empty_like = torch.empty_like(empty)
empty_like

tensor([[6.3058e-44, 6.7262e-44, 7.9874e-44],
        [6.3058e-44, 6.8664e-44, 7.0065e-44]])

### PyTorch methods exaples above

<div class = "alert alert-block alert-info">
    <b>The methods use above can be experimented on again and use Shift + Tab while on a method for more info</b>
</div>

<div class = 'alert alert-block alert-warning'>
    <b> Below is the code for CPU vs GPU comparison.</b>
</div>

In [14]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [15]:
%%time
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [16]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2) 

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

2.27888155
0.10399485
CPU times: total: 1.14 s
Wall time: 4.75 s


In [17]:
#Define probability tensor, will be using the same techniques to predict what comes next

probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [18]:
# This will be used for generating text given the context

tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [19]:
# tril = triangle lower, important for predicting the integers in future
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
# trui = triangle upper, important for predicting the integers in future
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [21]:

out = torch.zeros(5,5). masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [22]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
# transposing, the transpose function flipped the dimension from 2,3,4 to 4,3,2
input = torch.zeros(2,3,4)
out = input.transpose(0, 2) # swapping the 0th position with 2nd
out.shape

torch.Size([4, 3, 2])

In [24]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# stack the tensors along a new dimensions
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# importing nn from torch.nn
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([ 2.1173, -1.8186, -1.3831], grad_fn=<SqueezeBackward4>)


In [26]:
import torch.nn.functional as f

# create tensor
tensor1 = torch.tensor([1., 2., 3.])

#apply softmax using torch.nn.functional.softmax()
softmax_output = f.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [27]:
# initialize embedding vector
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#apply embedding layer
embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


<div class = 'alert alert-box alert-info'>
    <b>Matrix Multiplication</b>
</div>

In [28]:
import torch as t
# 3x2 with 2x3 matrix multiplication 
a = t.tensor([[1,2],[3,4],[5,6]])
b = t.tensor([[7,8,9],[10,11,12]])
#print(a@b)
print(t.matmul(a,b))
print("Both are same")
print(a@b)

# data types of both the matrices must be the same

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Both are same
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [32]:
#logits are floating point numbers that are the input to the softmax function
a = torch.rand(2, 3, 5)
print(a.shape)
x,y,z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])
